### ISSUE TITLE
GettingStarted.playground produces runtime error

### ISSUE THREAD

**Issue by arielelkin** [albertodebortoli/Promis#10]
1. Using Xcode 10.2.1
1. cloned repository and ran `pod install` in `/Example`.
1. Open and run `GettingStarted.playground`

```
error: GettingStarted.playground:15:5: error: use of unresolved identifier 'getData'
    getData(request: request).thenWithResult { data in
    ^~~~~~~

error: GettingStarted.playground:17:9: error: use of unresolved identifier 'parse'
        parse(data: data)
        ^~~~~

error: GettingStarted.playground:20:13: error: use of unresolved identifier 'map'
            map(data: parsedData)
            ^~~
```

**Comment by arielelkin** [comment]
@albertodebortoli  any updates?

**Comment by albertodebortoli** [comment]
Hi @arielelkin, sorry for the delay.
I cannot see the errors you reported in the playground when using Xcode 10.2.1.
There was another error though, which has now been fixed with #11.

![Screenshot 2019-05-03 at 13 41 39](https://user-images.githubusercontent.com/653112/57137914-2807a100-6da9-11e9-9860-3299299e5681.png)

Can you try the latest commit on master please? Make sure you open `Promis.xcworkspace` first and then the playground file from Xcode.

**Comment by arielelkin** [comment]
I pulled the latest commit, `5e9cb5b1e979d0915f154a539619474e3bb3c9ab` and I'm using Xcode 10.2.1 too

still getting the same error from a fresh install:

![image](https://user-images.githubusercontent.com/1756909/57370248-97a1d580-7187-11e9-98c7-7781b186e839.png)

This happens if I click on the playground's left gutter, after I build successfully.

**Comment by albertodebortoli** [comment]
I tried cloning the project from scratch, running pod install, opening the workspace, building, running the playground. I'm still getting the same positive outcome from my screenshot above + I'm on Xcode 11.2.1 now. I'm puzzled...
